"""
Dette er en tegning av et hus med en dør og et vindu.
"""

import turtle
#Start by turning the turtle upwards
turtle.left(90)

#Making the house
turtle.fillcolor("blue")
turtle.begin_fill()
turtle.forward(150)
turtle.left(90)
turtle.forward(40)
turtle.right(150)
turtle.forward(200)
turtle.right(60)
turtle.forward(200)
turtle.right(150)
turtle.forward(40)
turtle.left(90)
turtle.forward(150)
turtle.right(90)
turtle.forward(266.4)
turtle.end_fill()
turtle.penup()

#Adding a door
turtle.right(180)
turtle.forward(60)
turtle.left(90)
turtle.pendown()
turtle.fillcolor("Black")
turtle.begin_fill()
turtle.forward(100)
turtle.right(90)
turtle.forward(40)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(40)
turtle.end_fill()

#Adding a window
turtle.penup()
turtle.left(180)
turtle.forward(80)
turtle.left(90)
turtle.forward(40)
turtle.pendown()
turtle.fillcolor("Yellow")
turtle.begin_fill()
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(50)
turtle.end_fill()
turtle.right(180)
turtle.forward(25)
turtle.left(90)
turtle.pendown()
turtle.forward(50)
turtle.penup()
turtle.left(90)
turtle.forward(25)
turtle.left(90)
turtle.forward(25)
turtle.left(90)
turtle.pendown()
turtle.forward(50)

turtle.done()
